name: RUN SCRIPT LISTA
on:
  push:
    branches: [ main, master ]
    paths:
      - 'scripts/lista.py'
  schedule:
    - cron: '0 */2 * * *'  # Esegui ogni 2 ore
  workflow_dispatch:  # Consente l'esecuzione manuale

jobs:
  extract-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessario per il commit
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install blinker==1.4 selenium-wire undetected-chromedriver requests beautifulsoup4 lxml playwright bs4 rapidfuzz fuzzywuzzy python-Levenshtein python-dateutil python-dotenv selenium webdriver-manager pillow
          playwright install 

      - name: Run Script
        run: |
          python scripts/lista.py
      
      - name: Synchronize with remote and rebase
        run: |
          git config pull.rebase true
          git pull origin main
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ðŸ“Š Update list - ${{ github.run_number }}"
          # Aggiungi qui i file generati da lista.py se non sono giÃ  tracciati
          # file_pattern: "lista_output.txt" 
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
